### ISSUE TITLE
Proguard problem (JodaTime)

### ISSUE THREAD

**Issue by Adham32** [Synerise/android-sdk#13] opened 2024-02-20 16:58 UTC
Hello,

I have a problem after adding your sdk to an Android project.

Despite adding according to Proguard rules instructions, I still get this error:

```
Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.utils.b: Missing class org.joda.convert.FromString (referenced from: org.joda.time.DateTimeZone org.joda.time.DateTimeZone.forID(java.lang.String))
```

Trying to solve the problem I added such rules:

`
-keep class org.joda.** { *; }
-dontwarn org.joda.convert.FromString
-dontwarn org.joda.convert.ToString
-keep @org.joda.convert.FromString class *
-keepclassmembers class * {
    @org.joda.convert.FromString *;
}
-keep @org.joda.convert.ToString class *
-keepclassmembers class * {
    @org.joda.convert.ToString *;
}`

After building the project in the 'release' version, I get this error from your sdk:

```
Error while processing definitions: Unable to create call adapter for class eu.e for method InAppApi.getDefinitions
```

Can I get your help on this problem?

I am using version 5.14.0 of Synerise sdk

**Comment by konned** [comment] 2024-02-21 08:23
Hi, I am investigating the problem.

**Comment by konned** [comment] 2024-02-21 08:37
Do you have this rules?  :
```
# keep entire Synerise SDK
-keep class com.synerise.sdk.** { *; }
-keepclassmembers class com.synerise.sdk.** { *; }
-keepclassmembers class com.synerise.sdk.** {
    public <init>();
}
```

**Comment by Adham32** [comment] 2024-02-21 09:42
@konned Yes I have. The problem exists despite adding to Proguard rules from: https://hub.synerise.com/developers/mobile-sdk/installation-and-configuration/android/

**Comment by konned** [comment] 2024-02-21 09:47
@Adham32 Can you provide me your obfuscation config in release mode? Because I cannot reproduce this issue.

**Comment by Adham32** [comment] 2024-02-21 10:05
@konned Which config file do you mean? proguard-rules.pro?

**Comment by konned** [comment] 2024-02-21 10:07
Your release config in build.gradle of your app.

**Comment by Adham32** [comment] 2024-02-21 10:21
@konned 
```
  buildTypes {
        getByName("release") {
            isMinifyEnabled = true

            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )

            signingConfig = signingConfigs.getByName("release")
        }
    }
 ```

**Comment by konned** [comment] 2024-02-21 10:25
What is your compileSDK, and targetSDKVersion? Add to your proguard this line: 
`-printconfiguration "build/outputs/mapping/configuration.txt"`
and check if you have some keep rules for this path: com.synerise.sdk.injector.inapp

**Comment by Adham32** [comment] 2024-02-21 10:37
Now I have this issue when try to build app:

```
> Task :app:minifyDevReleaseWithR8 FAILED
AGPBI: {"kind":"error","text":"Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /*/app/build/outputs/mapping/devRelease/missing_rules.txt.","sources":[{}]}
AGPBI: {"kind":"error","text":"Missing class org.joda.convert.FromString (referenced from: org.joda.time.DateTimeZone org.joda.time.DateTimeZone.forID(java.lang.String))\nMissing class org.joda.convert.ToString (referenced from: java.lang.String org.joda.time.DateTimeZone.getID() and 5 other contexts)","sources":[{}],"tool":"R8"}

Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /*/app/build/outputs/mapping/devRelease/missing_rules.txt.

Missing class org.joda.convert.FromString (referenced from: org.joda.time.DateTimeZone org.joda.time.DateTimeZone.forID(java.lang.String))
```
Missing class org.joda.convert.ToString (referenced from: java.lang.String org.joda.time.DateTimeZone.getID() and 5 other contexts)

**Comment by konned** [comment] 2024-02-21 10:46
`-keep class org.joda.** { *; }
-dontwarn org.joda.convert.FromString
-dontwarn org.joda.convert.ToString`
Add this to your proguard.

**Comment by Adham32** [comment] 2024-02-21 11:01
@konned Ok, the app is building, and now when the app started, I got the log:
```
Synerise SDK           E   Error while processing definitions: Unable to create call adapter for class eu.e for method InAppApi.getDefinitions
```

**Comment by konned** [comment] 2024-02-21 11:04
Can you check build/outputs/mapping/configuration.txt and search for com.synerise.sdk.injector.inapp rules?

**Comment by ikurek** [comment] 2024-02-21 11:30
I think I have identified the issue - the problem seems to be obfuscation of classes used by Synerise SDK, for our case these dependencies were causing the issue:

* JodaTime - problem with `toString`/`fromString` converters, this one was compile-time so we were able to spot it because our CI build failed the release variants
* Retrofit - this is the source of `Unable to create call adapter for class *` @Adham32 mentioned before. Used in `Tracker.send()` method, not visible in compile-time, but causes Synerise SDK to throw exception in runtime when `Tracker.send()` is used
* Gson - issue with TypeToken usage, the same case as above

To solve it we had to manually include proguard configuration files for those dependencies, in the end the Synerise SDK configuration looks like this:
```
# keep entire Synerise SDK
-keep class com.synerise.sdk.** { *; }
-keepclassmembers class com.synerise.sdk.** { *; }
-keepclassmembers class com.synerise.sdk.** {
    public <init>();
}

# Keep JodaTime classes and converters
-dontwarn org.joda.convert.**
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }
-keep interface org.joda.time.** { *; }

# Rules required by Retrofit (Synerise SDK dependency)
# https://github.com/square/retrofit/blob/trunk/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro
-keepattributes Signature, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepattributes AnnotationDefault
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn javax.annotation.**
-dontwarn kotlin.Unit
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface * extends <1>
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-if interface * { @retrofit2.http.* public *** *(...); }
-keep,allowoptimization,allowshrinking,allowobfuscation class <3>
-keep,allowobfuscation,allowshrinking class retrofit2.Response

# Rules required by Gson (Synerise SDK dependency)
# https://github.com/google/gson/blob/main/examples/android-proguard-example/proguard.cfg
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { <fields>; }
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```
And it seems to be working - the crashes are gone and SDK started tracking events in release variants of the app.

Would it be possible to update the SDK and include those proguard rules? I don't think we should add them manually 🤔

**Comment by konned** [comment] 2024-02-21 11:35
@ikurek yes this is exactly the problem. However I cannot reproduce this issue on my side which is weird. What version of android studio are you using? 
I will add this rules to proguard config in next release.

**Comment by konned** [comment] 2024-02-21 13:19
@ikurek we have a lot of proguard rules for our dependencies. I will recheck them. Probably we forgot about retrofit because everyone uses retrofit in their apps. 
I will let you know when fix will be released.

**Comment by konned** [comment] 2024-02-22 23:57
5.14.1 has been released.

**Closed** 2024-03-07 11:25 UTC
